import {heroui} from "@heroui/theme"

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sf-pro-display)", "system-ui", "sans-serif"],
        display: ["var(--font-sf-pro-display)", "system-ui", "sans-serif"],
        text: ["var(--font-sf-pro-text)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
      },
      spacing: {
        "cus-xs": "var(--cus-spacing-xs)",
        "cus-sm": "var(--cus-spacing-sm)",
        "cus-md": "var(--cus-spacing-md)",
        "cus-lg": "var(--cus-spacing-lg)",
        "cus-xl": "var(--cus-spacing-xl)",
        "cus-2xl": "var(--cus-spacing-2xl)",
        "cus-3xl": "var(--cus-spacing-3xl)",
        "cus-4xl": "var(--cus-spacing-4xl)",
      },
      fontSize: {
        "cus-xs": ["var(--cus-font-size-xs)", { lineHeight: "var(--cus-line-height-xs)" }],
        "cus-sm": ["var(--cus-font-size-sm)", { lineHeight: "var(--cus-line-height-sm)" }],
        "cus-base": ["var(--cus-font-size-base)", { lineHeight: "var(--cus-line-height-base)" }],
        "cus-lg": ["var(--cus-font-size-lg)", { lineHeight: "var(--cus-line-height-lg)" }],
        "cus-xl": ["var(--cus-font-size-xl)", { lineHeight: "var(--cus-line-height-xl)" }],
        "cus-2xl": ["var(--cus-font-size-2xl)", { lineHeight: "var(--cus-line-height-2xl)" }],
        "cus-3xl": ["var(--cus-font-size-3xl)", { lineHeight: "var(--cus-line-height-3xl)" }],
      },
      fontWeight: {
        "cus-normal": "var(--cus-font-weight-normal)",
        "cus-medium": "var(--cus-font-weight-medium)",
        "cus-semibold": "var(--cus-font-weight-semibold)",
        "cus-bold": "var(--cus-font-weight-bold)",
      },
      borderRadius: {
        "cus-none": "var(--cus-radius-none)",
        "cus-sm": "var(--cus-radius-sm)",
        "cus-md": "var(--cus-radius-md)",
        "cus-lg": "var(--cus-radius-lg)",
        "cus-xl": "var(--cus-radius-xl)",
        "cus-2xl": "var(--cus-radius-2xl)",
        "cus-full": "var(--cus-radius-full)",
      },
      boxShadow: {
        "cus-card1": "var(--cus-shadow-card1)",
        "cus-card2": "var(--cus-shadow-card2)",
        "cus-card3": "var(--cus-shadow-card3)",
        "cus-drop": "var(--cus-shadow-drop)",
        "cus-card": "var(--cus-shadow-card)",
        "cus-light": "var(--cus-shadow-light)",
        "cus-footer": "var(--cus-shadow-footer)",
        "cus-menu": "var(--cus-shadow-menu)",
        "cus-cart": "var(--cus-shadow-cart)",
      },
      zIndex: {
        "cus-base": "var(--cus-z-base)",
        "cus-base-elevated": "var(--cus-z-base-elevated)",
        "cus-base-high": "var(--cus-z-base-high)",
        "cus-footer": "var(--cus-z-footer)",
        "cus-mobile-header": "var(--cus-z-mobile-header)",
        "cus-desktop-header": "var(--cus-z-desktop-header)",
        "cus-bottom-navigation": "var(--cus-z-bottom-navigation)",
        "cus-add-cart-button": "var(--cus-z-add-cart-button)",
        "cus-search-overlay": "var(--cus-z-search-overlay)",
        "cus-category-overlay": "var(--cus-z-category-overlay)",
        "cus-sidebar": "var(--cus-z-sidebar)",
        "cus-loading": "var(--cus-z-loading)",
        "cus-overlay-low": "var(--cus-z-overlay-low)",
        "cus-overlay-medium": "var(--cus-z-overlay-medium)",
        "cus-heroui-overlay": "var(--cus-z-heroui-overlay)",
        "cus-dropdown": "var(--cus-z-dropdown)",
        "cus-select": "var(--cus-z-select)",
        "cus-select-search": "var(--cus-z-select-search)",
        "cus-heroui-menu": "var(--cus-z-heroui-menu)",
        "cus-datepicker": "var(--cus-z-datepicker)",
        "cus-password-toggle": "var(--cus-z-password-toggle)",
        "cus-popover": "var(--cus-z-popover)",
        "cus-popover-advanced": "var(--cus-z-popover-advanced)",
        "cus-tooltip": "var(--cus-z-tooltip)",
        "cus-heroui-tooltip": "var(--cus-z-heroui-tooltip)",
        "cus-heroui-modal": "var(--cus-z-heroui-modal)",
        "cus-modal-backdrop": "var(--cus-z-modal-backdrop)",
        "cus-modal": "var(--cus-z-modal)",
        "cus-modal-high": "var(--cus-z-modal-high)",
        "cus-fullscreen": "var(--cus-z-fullscreen)",
        "cus-critical-backdrop": "var(--cus-z-critical-backdrop)",
        "cus-critical-modal": "var(--cus-z-critical-modal)",
        "cus-payment": "var(--cus-z-payment)",
        "cus-heroui-toast": "var(--cus-z-heroui-toast)",
        "cus-toast": "var(--cus-z-toast)",
        "cus-notification": "var(--cus-z-notification)",
      },
      transitionDuration: {
        "cus-fast": "var(--cus-transition-fast)",
        "cus-normal": "var(--cus-transition-normal)",
        "cus-slow": "var(--cus-transition-slow)",
        "cus-slower": "var(--cus-transition-slower)",
      },
      colors: {
        primary: {
          DEFAULT: "var(--color-primary)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
        },
        scarlet: {
          red: "var(--color-scarlet-red)",
        },
        red: {
          100: "var(--color-red-100)",
          80: "var(--color-red-80)",
          60: "var(--color-red-60)",
          20: "var(--color-red-20)",
          5: "var(--color-red-05)",
          2: "var(--color-red-02)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          80: "var(--color-secondary-80)",
          60: "var(--color-secondary-60)",
          20: "var(--color-secondary-20)",
        },
        neutral: {
          110: "var(--color-neutral-110)",
          100: "var(--color-neutral-100)",
          80: "var(--color-neutral-80)",
          60: "var(--color-neutral-60)",
          40: "var(--color-neutral-40)",
          20: "var(--color-neutral-20)",
          10: "var(--color-neutral-10)",
          5: "var(--color-neutral-05)",
          2: "var(--color-neutral-02)",
        },
        subtle: "var(--color-subtle)",
        "dark-green": "var(--color-dark-green)",
        "light-green": "var(--color-light-green)",
        "dark-warning": "var(--color-dark-warning)",
        "light-warning": "var(--color-light-warning)",
        "light-warning-2": "var(--color-light-warning-2)",
        "dark-red": "var(--color-dark-red)",
        "light-red": "var(--color-light-red)",
        "dark-blue": "var(--color-dark-blue)",
        "blue-100": "var(--color-blue-100)",
        "light-blue": "var(--color-light-blue)",
        "deep-gray": "var(--color-deep-gray)",
        "border-gray": "var(--color-border-gray)",
        "tag-gray": "var(--color-tag-gray)",
        "border-gray-2": "var(--color-border-gray-2)",
        "pine-blue": "var(--color-pine-blue)",
        grey: "var(--color-grey)",
        "light-blue-2": "var(--color-light-blue-2)",
        "light-active": "var(--color-light-active)",
      },
    },
  },
  plugins: [
    heroui({
      // Layout tokens - customize globally
      // These apply to all HeroUI components
      layout: {
        borderRadius: {
          small: "0.25rem", // 4px - var(--cus-radius-sm)
          medium: "0.5rem", // 8px - var(--cus-radius-md)
          large: "0.75rem", // 12px - var(--cus-radius-lg)
        },
        borderWidth: {
          small: "1px",
          medium: "2px",
          large: "3px",
        },
        disabledOpacity: 0.5,
      },
      themes: {
        light: {
          colors: {
            primary: {
              DEFAULT: "#007044",
              50: "#eef6f3",
              100: "#eef6f3",
              200: "#d9eae3",
              300: "#b0d3c5",
              400: "#007044",
              500: "#00653d",
              600: "#005a36",
              700: "#005433",
              800: "#004329",
              900: "#00321f",
              950: "#002718",
            },
            secondary: {
              DEFAULT: "#111827",
              80: "#1f2937",
              60: "#4e4e4e",
              20: "#a7a7a7",
            },
            danger: {
              DEFAULT: "#ff4850",
              50: "#fffafb",
              100: "#fef2f5",
              200: "#fcccd6",
              300: "#f56685",
              400: "#f1335c",
              500: "#ee0033",
            },
            warning: {
              DEFAULT: "#9c3f0f",
              50: "#fff8ec",
              100: "#f8e5ba",
            },
            success: {
              DEFAULT: "#0e6245",
              50: "#cbf4c9",
            },
            // Focus color
            focus: "#007044",
          },
        },
      },
    }),
  ],
}

module.exports = config;